### ISSUE TITLE
getDividends no longer works

### ISSUE THREAD

**Issue by salritchie2** [joshuaulrich/quantmod#297] opened 2020-02-11 01:16 UTC
### Description

`getDividends()` works sometimes but not others.

### Expected behavior

download of yahoo finance dividends for FCNTX

### Minimal, reproducible example

```r
FCNTXDIV <- getDividends('FCNTX', from = "2015-01-01")

Error in vapply(parse(text = fr[, 2]), eval, numeric(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 10
```

**Comment by joshuaulrich** [comment] 2020-02-11 12:40
Thanks for the report. I'm closing because this is a duplicate of #292 and #294. In the future, please search for similar issues and/or test to see if the development version is fixed.

**Closed by joshuaulrich** 2020-02-11 12:40 UTC

**Comment by salritchie2** [comment] 2020-02-11 17:44
Thank you.  But neither of these other issues references getDividends so I
will try to figure it out on my own.

Sally Ritchie

**Comment by joshuaulrich** [comment] 2020-02-12 00:23
@salritchie2 issue 294 references `getDividends()`.  Issue 292 is the root cause of the problem. `getDividends()` attempts to return dividends that are split-adjusted by default, so it calls `getSplits()`. The call to `getSplits()` fails, which throws the same error you report.

**Comment by salritchie2** [comment] 2020-02-12 00:33
Thank you.  This was helpful.  I did figure out what I needed to do by
adding the split.adjust parm, which solved the problem.
Sally Ritchie.
