### ISSUE TITLE
getFX() issue

### ISSUE THREAD

**Issue by jbnitorum** [joshuaulrich/quantmod#147] opened 2017-04-11 18:21 UTC
Looks like there is an issue with Oanda.  I can no longer successfully download FX data.  It looks like maybe Oanda requires a subscription now?  Error is below.  Tried accessing the URL mentioned in verbose mode directly but was not able to download a CSV.

```
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
In addition: Warning message:
In download.file(oanda.URL, destfile = tmp, quiet = !verbose) :
  downloaded length 15638 != reported length 200
```

**Comment by braverock** [comment] 2017-04-11 18:24
This is a duplicate of Issue #144, which has already been fixed in the current master branch.  Please see #144 and update to test.

**Closed by braverock** 2017-04-11 18:24 UTC
