### ISSUE TITLE
The data get from GetSymbols() are not include date index

### ISSUE THREAD

**Issue by Kalvinwu** [joshuaulrich/quantmod#169] opened 2017-06-19 06:03 UTC
### Description

I tried to use getSymbols() to download the NASDAQ data from google finance. However, index is NA.

### Expected behavior

I want to get the date information.

### Minimal, reproducible example

```r
library(quantmod)
getSymbols('QQQ',src = 'google')
index(QQQ)
```

### Console Info

###> index(QQQ)
   [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
  [36] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
  [71] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[ reached getOption("max.print") -- omitted 1632 entries ]

**Comment by joshuaulrich** [comment] 2017-06-19 22:32
I cannot reproduce this.  Please provide the output from `sessionInfo()`.

**Comment by joshuaulrich** [comment] 2017-08-30 10:00
Closing due to inability to reproduce and lack of user input.

**Closed by joshuaulrich** 2017-08-30 10:00 UTC

**Comment by StineLee** [comment] 2017-10-23 07:43
meet the same issue today

**Comment by StineLee** [comment] 2017-10-23 07:44
met the same issue today.
Hereby were the output:

R version 3.0.2 (2013-09-25)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.2             xlsx_0.5.7            xlsxjars_0.6.1       
 [4] rJava_0.9-6           lpSolve_5.6.11        lpSolveAPI_5.5.2.0-14
 [7] quantmod_0.4-4        TTR_0.22-0            xts_0.9-7            
[10] zoo_1.7-12           

loaded via a namespace (and not attached):
[1] assertthat_0.1  grid_3.0.2      lattice_0.20-31 parallel_3.0.2  Rcpp_0.11.5    
[6] tools_3.0.2

**Comment by joshuaulrich** [comment] 2017-10-23 09:07
@StineLee Can you please try to reproduce your issue with the current version of quantmod (and R)?  You're using R-3.0.2 and quantmod 0.4-4, but the current versions are R-3.4.2 and quantmod 0.4-11.  You should also consider upgrading xts and zoo.
