### ISSUE TITLE
getSymbols not working for Yahoo

### ISSUE THREAD

**Issue by bojanbis** [joshuaulrich/quantmod#158] opened 2017-05-18 03:36 UTC
getSymbols() seems to fail if the source is Yahoo; looks like Yahoo changed the link for historical data, so https://ichart.finance.yahoo.com/table.csv no longer works. Anybody has a clue how to fix this?

**Comment by joshuaulrich** [comment] 2017-05-18 13:49
Closing as duplicate of #157.

**Closed by joshuaulrich** 2017-05-18 13:49 UTC
