### ISSUE TITLE
getQuote generates error

### ISSUE THREAD

**Issue by shumakerro** [joshuaulrich/quantmod#396] opened 2023-07-28 01:07 UTC
### Description

getQuote('SPY', src = 'yahoo')
generates the following error:
Error in .yahooSession(TRUE) : Unable to get yahoo crumb
quantmod was properly patched in spring 2023 

### Expected behavior
current price

### Minimal, reproducible example

getQuote('SPY', src = 'yahoo')
```r

```
getQuote('SPY', src = 'yahoo')

### Session Info

```r
[Insert your sessionInfo() output]
```R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by joshuaulrich** [comment] 2023-07-28 13:48
Closing as duplicate of #393.

**Closed by joshuaulrich** 2023-07-28 13:48 UTC

**Comment by shumakerro** [comment] 2023-07-28 16:35
Thanks much Joshua, I got it working.

    On Friday, July 28, 2023 at 09:48:23 AM EDT, Joshua Ulrich ***@***.***> wrote:  
 
 


Closing as duplicate of #393.
