### ISSUE TITLE
getFX stopped working

### ISSUE THREAD

**Issue by hdiwan** [joshuaulrich/quantmod#121] opened 2016-09-07 05:34 UTC
> getFX('PKR/KES')
> Error in download.file(oanda.URL, destfile = tmp, quiet = !verbose) : 
>  cannot open URL 'http://www.oanda.com/currency/historical-rates/download?>quote_currency=PKR&end_date=2016-09-06&start_date=2015-04-26&period=daily&display=absolute&rate=0&data_range=y2&price=mid&view=table&base_currency_0=KES&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv'

Not sure if we'll need to change data providers or if OANDA's URLs have changed or what.

**Comment by joshuaulrich** [comment] 2016-09-07 10:47
Closing as duplicate of #83.

**Closed by joshuaulrich** 2016-09-07 10:47 UTC
Labels: duplicate
