### ISSUE TITLE
I can only get 5 xts

### ISSUE THREAD

**Issue by jw3315** [joshuaulrich/quantmod#127] opened 2016-12-02 07:23 UTC
I can only get 5 xts. 
That problem also appeared when I was writing a loop longer than 5 using `dailyReturn()`.
Need help.

```r
> tickersList <- stockSymbols()
> set.seed(3);sample.stocks<-sample(tickersList$Symbol,10)
> data.stocks<-new.env()
> getSymbols(sample.stocks,env=data.stocks,from=as.Date("2016-01-01"), to = as.Date("2016-11-01"))
pausing 1 second between requests for more than 5 symbols
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot download all files
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  URL 'http://ichart.finance.yahoo.com/table.csv?s=CBB-PB&a=0&b=01&c=2016&d=10&e=01&f=2016&g=d&q=q&y=0&z=CBB-PB&x=.csv': status was '404 Not Found'
```

**Comment by joshuaulrich** [comment] 2016-12-02 12:34
I'm closing this as invalid because it's not a bug.  The error in `download.file` is because the Yahoo Finance server returned a 404 error (page not found).  That means Yahoo Finance doesn't provide historical data as a CSV for ticker `"CBB-PB"`.  There is no guarantee that the tickers returned by `stockSymbols` will have historical data available at Yahoo Finance, Google Finance, or any other public source.

----

Here is some background on `stockSymbols`.  The *Details* section of `?stockSymbols` says,

> 'stockSymbols' fetches instrument symbols from the nasdaq.com website, and adjusts the symbols to be compatible with the Yahoo! Finance website.

And the *Note* section of `?stockSymbols` says,

>  The symbols returned by 'stockSymbols' may not be in the format necessary to retrieve data using 'getYahooData'.

So the tickers returned by `stockSymbols` are not pull from Yahoo Finance, and they may not be in the correct format to pull from Yahoo Finance.  The `stockSymbols` source code has these comments regarding the ticker symbol format:

```r
  # See "NYSE "behind the dot" or Nasdaq 5th-letter codes and other special
  # codes" here:
  # http://en.wikipedia.org/wiki/Ticker_symbol
  # http://help.yahoo.com/l/us/yahoo/finance/quotes/quote-02.html
  # 
  # AMEX / NYSE Mappings (NASDAQ doesn't need transformation?):
  # Exchanges -> Yahoo
  # /WS       -> -WT
  # /U        -> -U
  # .[A-Z]    -> NA (special notes/bonds - IG)
  # :[AP]     -> NA (after-hours / pre-market)
  # ^         -> -P
  # /         -> -
  # $         -> NA (NYSE Only)
  # ~         -> NA (NYSE Only)
```

**Closed by joshuaulrich** 2016-12-02 12:34 UTC
