### ISSUE TITLE
Unable to download data from OANDA

### ISSUE THREAD

**Issue by wthielen** [joshuaulrich/quantmod#145] opened 2017-04-09 06:54 UTC
It looks like OANDA does not allow unregistered people to download CSV data anymore. When debugging with debugonce(getSymbols.oanda), I get the following oanda.URL:
https://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2017-04-09&start_date=2017-01-01&period=daily&display=absolute&rate=0&data_range=d180&price=mid&view=table&base_currency_0=JPY&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv

This is redirected to:
https://www.oanda.com/fx-for-business/historical-rates?quote_currency=USD&end_date=2017-04-09&start_date=2017-01-01&period=daily&display=absolute&rate=0&data_range=d180&price=mid&view=table&base_currency_0=JPY&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv

There is a download button, but it gives me a popup to register.

**Comment by joshuaulrich** [comment] 2017-04-09 12:42
Thanks for the report!  This is a duplicate of #144, so I'm closing this in order to keep the relevant information in one issue.

**Closed by joshuaulrich** 2017-04-09 12:42 UTC
Labels: duplicate
