### ISSUE TITLE
getSymbols error 

### ISSUE THREAD

**Issue by yihzhang** [joshuaulrich/quantmod#198] opened 2017-11-02 02:13 UTC
I always get error attached below when I tried to get data by using `getSymbol()`,but when I add `src="google"`, I can get the data. How can I get data without `src=...` ?

```r
> library(quantmod)
> getSymbols("AAPL",from = "2014-01-01", to = "2014-12-31",auto.assign = F) 
Error in ` colnames<- `(`*tmp*`, value = c("AAPL.Open", "AAPL.High", "AAPL.Low",  : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 
'/var/folders/p4/d1716x613c70sd0wq1r6hy3m0000gn/T//RtmpqIL0i9/file8ae2c0441c1'
```

**Comment by joshuaulrich** [comment] 2017-11-02 17:27
I cannot replicate this error.  Please provide the output of `sessionInfo()`.

**Comment by joshuaulrich** [comment] 2017-12-02 13:53
Closing because I cannot replicate and the user has provided no feedback in the past month.

**Closed by joshuaulrich** 2017-12-02 13:53 UTC

**Comment by meanreversal** [comment] 2019-10-08 14:17
Hello I have the exact same error .. and I'm unable to use getSymbols at all. I'm using MS Visual platform for R. SessionInfo included below the error

> getSymbols("AAPL")
Error in `colnames<-`(`*tmp*`, value = c("AAPL.Open", "AAPL.High", "AAPL.Low",  : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 'C:\XYZmadeup\AppData\Local\Temp\RtmpAXGLT5\file344018d8635e'


R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantmod_0.4-7                TTR_0.23-1                    curl_2.2                      tseries_0.10-35               gtable_0.2.0                 
 [6] readxl_0.1.1                  scales_0.4.0                  lubridate_1.6.0               PerformanceAnalytics_1.4.3541 xts_0.9-7                    
[11] zoo_1.7-13                    dplyr_0.5.0                   purrr_0.2.2                   readr_1.0.0                   tidyr_0.6.0                  
[16] tibble_1.2                    ggplot2_2.1.0                 tidyverse_1.0.0               RevoUtilsMath_10.0.0          RevoUtils_10.0.2             
[21] RevoMods_10.0.0               MicrosoftML_1.0.0             mrsdeploy_1.0                 RevoScaleR_9.0.1              lattice_0.20-34              
[26] rpart_4.1-10                 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7            plyr_1.8.4             iterators_1.0.8        tools_3.3.2            jsonlite_1.1           mrupdate_1.0.0        
 [7] foreach_1.4.3          DBI_0.5-1              CompatibilityAPI_1.1.0 stringr_1.1.0          rtvs_1.0.0.0           R6_2.2.0              
[13] magrittr_1.5           codetools_0.2-15       assertthat_0.1         colorspace_1.2-7       quadprog_1.5-5         stringi_1.1.2         
[19] munsell_0.4.3

**Comment by gcpoole** [comment] 2020-06-09 22:44
I am getting the same error.  Interestingly, it only occurs when I specify the "to" parameter.

```
>quantmod::getSymbols("^GSPC", from = "2020-01-01", "2020-01-05")
Error in as.environment(where) : 
  no item called "2020-01-05" on the search list
> quantmod::getSymbols("^GSPC", from = "2020-01-01", to = "2020-01-05")
[1] "^GSPC"
Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on 'https://query1.finance.yahoo.com/v7/finance/download/^GSPC?period1=1577836800&period2=1578182400&interval=1d&events=history&crumb=QG5QBIaZNdf'
```
And, the "to" date is missing from the data set.

I wonder if yahoo returns something a bit differently when the "to" variable is specified?

```
R version 4.0.0 (2020-04-24) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 18362)  Matrix products: default  locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] stocker_0.1.0  loaded via a namespace (and not attached): [1] zoo_1.8-8       compiler_4.0.0  tools_4.0.0     xts_0.12-0      curl_4.3        quantmod_0.4.17 grid_4.0.0      TTR_0.23-6      lattice_0.20-41
--
```

**Comment by joshuaulrich** [comment] 2020-06-21 16:01
@gcpoole thanks for that example! You say you get the same error, but your example only shows the warning. I only seem to get the warning when the amount of time between 'from' and 'to' is small.

Do you have an example that throws the error in the original report?

The missing 'to' date is probably caused by #258.

**Comment by gcpoole** [comment] 2020-06-22 21:51
@joshuaulrich, I apologize.  I was looking at a number of different threads regarding this issue and I think I must have posted to the wrong one.  You are correct -- there is no error, only the warning.  Yes, my issue looks similar to #258

**Comment by joshuaulrich** [comment] 2020-06-23 16:41
@gcpoole no worries! Thanks for checking and responding quickly.
