### ISSUE TITLE
Yahoo ?! changed again

### ISSUE THREAD

**Issue by fpa2** [joshuaulrich/quantmod#173] opened 2017-06-22 01:25 UTC
It seems that Yahoo changed their scripts again. 

> getSymbols("XLF", from="2016-09-13")
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot open URL 'https://ichart.finance.yahoo.com/table.csv?s=XLF&a=8&b=13&c=2016&d=5&e=22&f=2017&g=d&q=q&y=0&z=XLF&x=.csv'
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  InternetOpenUrl failed: 'A connection with the server could not be established'

The new link is something like
https://query1.finance.yahoo.com/v7/finance/download/XLF?period1=1495416278&period2=1498094678&interval=1d&events=history&crumb=JRLgiAGEzO.

where the dates are in unix...

**Comment by joshuaulrich** [comment] 2017-06-22 01:41
Closing as duplicate of #157. This has been fixed for almost a month.  Even though you didn't provide the output from `sessionInfo()` that the contributing guidelines ask for, I can tell you're using an old version because the `https://ichart.finance.yahoo.com` URL hasn't been used since 0.4-8.

**Closed by joshuaulrich** 2017-06-22 01:41 UTC
