### ISSUE TITLE
getQuote error: unable to get yahoo crumb

### ISSUE THREAD

**Issue by Beliavsky** [joshuaulrich/quantmod#397] opened 2023-07-28 01:08 UTC
Using R version 4.3.1

```
library("quantmod")
x = getQuote("SPY")
```
gives

`Error in .yahooSession(TRUE) : unable to get yahoo crumb`

**Comment by joshuaulrich** [comment] 2023-07-28 13:48
Duplicate of https://github.com/joshuaulrich/quantmod/issues/393.

**Closed by joshuaulrich** 2023-07-28 13:48 UTC
