### ISSUE TITLE
getSymbols()  doesn't work

### ISSUE THREAD

**Issue by Lifu2017** [joshuaulrich/quantmod#204] opened 2017-12-01 03:03 UTC
### Hi, tonight getSymbols(), getDividends() doesn't work, it was working last night. 

When I enter this: 
getSymbols('MSFT',src='yahoo')

Result is as following: 
> getSymbols('MSFT',src='yahoo')
Warning: MSFT download failed; trying again.
Error: MSFT download failed after two attempts. Error message:
HTTP error 400.

### My Session Info
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.6 (Sierra)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-11 TTR_0.23-2      xts_0.10-0      zoo_1.7-14     

loaded via a namespace (and not attached):
[1] tools_3.3.1     curl_2.8.1      grid_3.3.1      lattice_0.20-33

**Comment by joshuaulrich** [comment] 2017-12-01 11:59
Please search issues before creating a new one.  This is a duplicate of #202.

**Closed by joshuaulrich** 2017-12-01 11:59 UTC
