### ISSUE TITLE
geysymbols 

### ISSUE THREAD

**Issue by sunzhouziguang** [joshuaulrich/quantmod#186] opened 2017-08-26 10:46 UTC
I can't get Chinese stock data now, from YAHOO Finance.My teacher said, YAHOO finance changed the link, need to download the new QUANTMOD, what should I do?

getSymbols("0001979.ss",src='yahoo',from="2013-08-20",to="2016-09-02")
Warning: 0001979.ss download failed; trying again.
Error: 0001979.ss download failed after two attempts. Error message:
HTTP error 404.

**Comment by joshuaulrich** [comment] 2017-08-26 10:53
Please follow the [contributing guide](https://github.com/joshuaulrich/quantmod/blob/master/CONTRIBUTING.md), provide the information requested in the issue template, and do not open an issue to ask a question.  The issue tracker is for bugs and feature requests, not user support.

Closing as duplicate of #185.

**Closed by joshuaulrich** 2017-08-26 10:53 UTC
Labels: duplicate
