### ISSUE TITLE
Error in curl::curl_download(cu, tmp, handle = h) 

### ISSUE THREAD

**Issue by Jansoto** [joshuaulrich/quantmod#249] opened 2018-10-11 20:15 UTC
### Description

After installing quantmod package I ran getSymbols("AAPL") and I got the error below.
Please advise.

### Expected behavior

Error in curl::curl_download(cu, tmp, handle = h) : 
  Timeout was reached: Connection timed out after 10015 milliseconds

### Session Info

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-13 TTR_0.23-4      xts_0.11-1      zoo_1.8-4      

loaded via a namespace (and not attached):
[1] compiler_3.5.1  tools_3.5.1     curl_3.2        grid_3.5.1      lattice_0.20-35

**Comment by joshuaulrich** [comment] 2018-10-13 13:14
I agree with @j450h1. This is likely specific to your internet connection, so I'm going to close this issue.  You are welcome to continue discussion to try and diagnose the root cause of the problem.

**Closed by joshuaulrich** 2018-10-13 13:14 UTC
