### ISSUE TITLE
getSymbols() return wrong "Open", "High", "Low" data [BUG]

### ISSUE THREAD

**Issue by fc1984** [joshuaulrich/quantmod#181] opened 2017-07-22 11:19 UTC
### Description
I found a bug in getSymbols() function (quantmod library). This function return wrong data for columns "Open", "High", "Low".

### Expected behavior
If you plot the chartSeries of FBK.MI you can see that before April 2017 "Open" price is ALWAYS greater then "Close" Price.
That is strange and wrong, to confirm the bug I compared prices returned from getSymbols() 
```r
> FBK.MI['2017-04-10']
           FBK.MI.Open FBK.MI.High FBK.MI.Low FBK.MI.Close FBK.MI.Volume FBK.MI.Adjusted
2017-04-10       6.611       6.695      6.564         6.38       2087223         6.09912
> FBK.MI['2017-02-14']
           FBK.MI.Open FBK.MI.High FBK.MI.Low FBK.MI.Close FBK.MI.Volume FBK.MI.Adjusted
2017-02-14       5.706       5.759      5.643         5.48       2102413        5.238742
```
with prices I find on yahoo page 
```r
https://it.finance.yahoo.com/quote/FBK.MI/history?period1=1460239200&period2=1491775200&interval=1d&filter=history&frequency=1d
	 FBK.MI.Open FBK.MI.High FBK.MI.Low FBK.MI.Close FBK.MI.Volume FBK.MI.Adjusted
10 apr 2017	6,32	    6,40       6,28	    6,38     2.087.223            6,10	
https://it.finance.yahoo.com/quote/FBK.MI/history?period1=1455404400&period2=1487026800&interval=1d&filter=history&frequency=1d
	 FBK.MI.Open FBK.MI.High FBK.MI.Low FBK.MI.Close FBK.MI.Volume FBK.MI.Adjusted
14 feb 2017	5,45	    5,51       5,39	    5,48     2.102.413            5,24
```
and they are different.

I tested different symbols of BIT (FBK.MI, STM.MI, G.MI, ENI.MI, ENEL.MI) they have the same problems.
I am pretty sure that this bug was absent one or two months ago.

### Minimal, reproducible example
```r
library(quantmod)
getSymbols('FBK.MI', src='yahoo',  auto.assign=TRUE)	
chartSeries(FBK.MI['2017'])
FBK.MI['2017-04-10']
FBK.MI['2017-02-14']
```

### Session Info

```r
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantmod_0.4-9       TTR_0.23-1           xts_0.9-7            zoo_1.7-13           RevoUtilsMath_10.0.0
 [6] RevoUtils_10.0.3     RevoMods_11.0.0      MicrosoftML_1.3.0    mrsdeploy_1.1.0      RevoScaleR_9.1.0    
[11] lattice_0.20-34      rpart_4.1-10        

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       CompatibilityAPI_1.1.0 foreach_1.4.3          grid_3.3.3             R6_2.2.0              
 [6] jsonlite_1.3           curl_2.3               iterators_1.0.8        tools_3.3.3            mrupdate_1.0.1   
```

**Comment by joshuaulrich** [comment] 2017-07-22 23:11
Thanks for the report.  I'm closing as a duplicate of #174.  This might not be an *exact* duplicate, but it should be fixed as part of the previously-reported issue.  I also removed the "[BUG]" from the title, because GitHub has labels for repository owners to categorize issues.

**Closed by joshuaulrich** 2017-07-22 23:11 UTC
