### ISSUE TITLE
getQuote using .cvs at Yahoo shut down

### ISSUE THREAD

**Issue by bluezep** [joshuaulrich/quantmod#199] opened 2017-11-03 09:09 UTC
### Description
Yahoo has  shut down .csv quotes on 11/01/2017 although reports are that Yahoo's jsonlite quotes is still working.
Initially error 999 then error changed to 'It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com.' and now error '403 forbidden'.
This was done without notification.  How long will Verizon keep the Jsonlite portal open?
Or really - when will Google or other getQuote() source be implemented?
Thanks,
Bluezep

[Describe the issue]

### Expected behavior

[Describe the behavior/output you expected]

### Minimal, reproducible example

```r
[Insert sample data and code]
URL 'http://download.finance.yahoo.com/d/quotes.csv?s=CPB+CCI&f=d1t1l1c1p2ohgv': status was '403 Forbidden'```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by joshuaulrich** [comment] 2017-11-03 10:38
Closing as duplicate of #197.

**Closed by joshuaulrich** 2017-11-03 10:38 UTC
