### ISSUE TITLE
getFX produces 404 error

### ISSUE THREAD

**Issue by rstub** [joshuaulrich/quantmod#226] opened 2018-04-06 09:04 UTC
### Description

Calling `getFX("USD/JPY")` function gives 404 error.

### Expected behavior

FX rates for USD/JPY should be downloaded and installed into the environment

### Minimal, reproducible example

```r
library(quantmod)
getFX("USD/JPY")
# Fehler in open.connection(con, "rb") : HTTP error 404.
```

### Session Info

```r
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-12 TTR_0.23-3      xts_0.10-2      zoo_1.8-1      

loaded via a namespace (and not attached):
[1] compiler_3.4.3  curl_3.2        grid_3.4.3      jsonlite_1.5   
[5] lattice_0.20-35
```

**Comment by rstub** [comment] 2018-04-06 09:07
This issue is motivated by a SO queation: https://stackoverflow.com/questions/49688058/quantmod-getfx-function-error
According to a comment there, it is related to using a deprecated version of oanda's the REST API.

**Comment by joshuaulrich** [comment] 2018-04-06 11:15
Thanks for the report.  Please search existing issues before taking time to write a report.  This is a duplicate of #225, which has already been fixed (but not yet in master).

**Closed by joshuaulrich** 2018-04-06 11:15 UTC

**Comment by rstub** [comment] 2018-04-06 11:16
Sorry for the noise. I only searched the open issues ... :-(

**Comment by joshuaulrich** [comment] 2018-04-06 11:38
No worries.  I'm happy you contributed a report, but sad you did it after the issue was already resolved.
