### ISSUE TITLE
Getting ^DFI index from Google?

### ISSUE THREAD

**Issue by for-coursera** [joshuaulrich/quantmod#146] opened 2017-04-10 05:48 UTC
Is it possible to get historical data for `NYSE ARCA DEFENSE INDEX` located [here](https://www.google.com/finance?cid=12974376)?

Thanks!

**Comment by joshuaulrich** [comment] 2017-04-10 13:14
No, because Google does not provide a CSV to download for that index.

Closing as invalid because this is not a bug in quantmod.

**Closed by joshuaulrich** 2017-04-10 13:14 UTC
