### ISSUE TITLE
Error with add_TA while addTA works

### ISSUE THREAD

**Issue by ignl** [joshuaulrich/quantmod#80] opened 2016-03-16 11:48 UTC
This code works:

```
library(quantmod)
startDate = '2006-01-01'
endDate = as.character(Sys.Date())
spyTs <- getSymbols("SPY", from = startDate, to = endDate, auto.assign = FALSE, verbose = FALSE)
spyMonthly <- to.monthly(spyTs)
chartSeries(spyMonthly)
addTA(spyMonthly$spyTs.High)
```

This one returns error:

```
spyMonthly <- to.monthly(spyTs)
chart_Series(spyMonthly)
add_TA(spyMonthly$spyTs.High)
```

> "Error in if (length(c(year, month, day, hour, min, sec)) == 6 && c(year,  : 
>   missing value where TRUE/FALSE needed"

**Comment by joshuaulrich** [comment] 2016-03-16 12:01
This appears to be caused by an issue in xts that has been fixed in the [development version on GitHub](https://github.com/joshuaulrich/xts).  I can replicate the error if I use xts_0.9-7 from CRAN, but your code works if I use the latest xts from GitHub (though there are still warnings for "In as_numeric(YYYY) : NAs introduced by coercion").

**Comment by ignl** [comment] 2016-03-16 12:11
Thanks Joshua, install_github("joshuaulrich/xts") fixed it for me.

**Comment by joshuaulrich** [comment] 2016-03-16 12:13
You're welcome.

Closing as 'invalid', since this wasn't an issue with quantmod.

**Closed by joshuaulrich** 2016-03-16 12:13 UTC
Labels: invalid
