### ISSUE TITLE
OANDA removed API access to download FX rates

### ISSUE THREAD

**Issue by wthielen** [joshuaulrich/quantmod#227] opened 2018-04-06 13:21 UTC
getFX is not working anymore: it returns a 404 in open.connection.

I checked out the OANDA URL it composes in getSymbols.oanda, and it seems that that URL indeed gives a 404.

The browser-accessible historical rates URL is here: https://www.oanda.com/fx-for-business/historical-rates
The CSV download option seems to be enabled only for Pro users, which requires a $75 monthly membership.

Alternative is to use the Yahoo source:

    USDJPY = getSymbols("USDJPY=X", src="yahoo", auto.assign = FALSE)

works OK, but I see discrepancies in the monthly results:

             USDJPY.Close
    Jan 2018      108.732
    Feb 2018      107.426
    Mar 2018      106.479

while I have registered them in my sheet (using the getFX function when OANDA was still working) as:

    2018 | 1 | 108.958
    2018 | 2 | 106.986
    2018 | 3 | 106.235

**Comment by wthielen** [comment] 2018-04-06 13:31
Also would probably need to update getSymbols to not add a Volume column for currencies.

**Comment by joshuaulrich** [comment] 2018-04-06 14:16
Closing as a duplicate of #225.

**Closed by joshuaulrich** 2018-04-06 14:16 UTC
