### ISSUE TITLE
getSymbols for currency pairs from oanda not downloading

### ISSUE THREAD

**Issue by donkeykonggithub** [joshuaulrich/quantmod#84] opened 2016-03-26 22:33 UTC
Having recent issues downloading currency pairs from oanda using getSymbols in quantmod 0.4-5. It appears the API may have changed:

```
> getSymbols("USD/EUR", src="oanda", from="2015-01-01", verbose=TRUE)

downloading  USD/EUR .....trying URL 'http://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2016-03-26&start_date=2015-01-01&period=daily&display=absolute&rate=0&data_range=y2&price=mid&view=table&base_currency_0=EUR&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv'

Error in download.file(oanda.URL, destfile = tmp, quiet = !verbose) : 
  cannot open URL 'http://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2016-03-26&start_date=2015-01-01&period=daily&display=absolute&rate=0&data_range=y2&price=mid&view=table&base_currency_0=EUR&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv'
```

Copy-pasting the URL into a browser still downloads a CSV, but the included data appears to be limited to a two-year period ending at the end_date. The error does not appear to be specific to particular currency pairs.

Series from other sources still work:
```
> getSymbols("^GSPC", src="yahoo", from="2015-01-01")
[1] "GSPC"
```

**Comment by joshuaulrich** [comment] 2016-03-26 22:38
What is your `sessionInfo()`?

**Comment by donkeykonggithub** [comment] 2016-03-27 00:08
```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-5 TTR_0.23-1     xts_0.9-7      zoo_1.7-12    

loaded via a namespace (and not attached):
[1] tools_3.2.4     grid_3.2.4      lattice_0.20-33

```

**Comment by joshuaulrich** [comment] 2016-03-27 00:14
Closing as duplicate of #83.

**Closed by joshuaulrich** 2016-03-27 00:14 UTC
