### ISSUE TITLE
Can only download data from Yahoo Finance for 100 symbols in one session

### ISSUE THREAD

**Issue by Beliavsky** [joshuaulrich/quantmod#363] opened 2022-05-21 22:05 UTC
I used to be able to download historical data for hundreds of symbols from Yahoo Finance using quantmod, but for the last few weeks the limit is 100, after which I get 

`HTTP error 401`

Has anyone else encountered this, and is there a workaround?

If I try again with new symbols after a few minutes, I immediately get the 401 error, but if I wait until the next day, I can again download 100 symbols. So there appears to be a daily quota.

**Comment by joshuaulrich** [comment] 2022-05-22 18:51
I'm going to mark this as a duplicate of #360, so we can keep the conversation there and in one place. I've pushed a branch that uses the JSON API instead of the CSV API. Please try that and let me know if it solves your issue.

**Closed by joshuaulrich** 2022-05-22 18:51 UTC
Labels: duplicate
