### ISSUE TITLE
Error: std::bad_alloc 

### ISSUE THREAD

**Issue by sureshvigneshbe** [joshuaulrich/quantmod#308] opened 2020-06-05 07:31 UTC
I am using R 3.6.0  version and having RAM memory 16 GB.
While using read excel  for reading two excel (xlsx files) got the error "Error: std::bad_alloc".

The two file sizes are respectively  166 MB (10 columns) and 130 MB (60 columns). 

As found one of thread , need to close and open R studio , will resolve this issue. 
Tried it and working now. But we have schedule (Automation)  this R script to load the excel files .

Could any one suggest any other work around on this issue. Also having sufficient ram memory. 

Thanks,
N Suresh

**Comment by joshuaulrich** [comment] 2020-06-05 11:19
Can you please clarify why you think this is an issue with quantmod?  Maybe you intended to post this to another repository?

"Error: std::bad_alloc" suggests the issue is with some C++ code.  None of quantmod's code (or any of its dependencies) use C++ code, so I highly doubt this is an issue with quantmod.  For that reason, I'm going to close this issue.  Please feel welcome to comment and I'll try to help track down the issue.

**Closed by joshuaulrich** 2020-06-05 11:19 UTC

**Comment by sureshvigneshbe** [comment] 2020-06-05 15:42
Sorry I try to post in read_excel under tidyverse. Sorry for the inconvenience.
