### ISSUE TITLE
getMetals or getSymbols with oanda not working for me

### ISSUE THREAD

**Issue by dmeloso** [joshuaulrich/quantmod#148] opened 2017-04-12 15:31 UTC
I successfully used the following code a few days back:
`getMetals('silver', from = '1900-01-01')`

Yesterday and today I have tried the same as above, but also the following:
`getMetals('silver')
getMetals('XAG')
getSymbols('XAGUSD', src = 'oanda')`

In all cases I get the following error:
`Error in carToDate(x):
character string is not in a standard unambiguous format`

In case it can be useful, I checked my sessionInfo and I run quantmod_0.4-7.

Any information about what may be failing, will be very appreciated. Thank you!

**Comment by joshuaulrich** [comment] 2017-04-12 15:31
Closing as duplicate of #144.

**Closed by joshuaulrich** 2017-04-12 15:31 UTC
