### ISSUE TITLE
getSymbols.yahoo returning adjusted OHLC

### ISSUE THREAD

**Issue by the-tourist-** [joshuaulrich/quantmod#180] opened 2017-07-20 14:57 UTC
### Description

getSymbols.yahoo is returning the adjusted values in OHLC instead of the unadjusted values that it previously would be expected to.  It should be returning the same values for <Close> as does getSymbols.google.

```
> getSymbols("VXX", src = "yahoo")
> head(VXX)
           VXX.Open VXX.High  VXX.Low VXX.Close VXX.Volume VXX.Adjusted
2009-01-30 25628.16 26890.24 25536.00  26772.48        800     26772.48
2009-02-02 27673.60 27673.60 26608.64  26688.00       1200     26688.00
2009-02-03 26659.84 26659.84 25423.36  25438.72        600     25438.72
2009-02-04 25152.00 25699.84 24832.00  25533.44        600     25533.44
2009-02-05 26009.60 26570.24 25126.40  25377.28        900     25377.28
2009-02-06 25344.00 25349.12 24335.36  25011.20        500     25011.20
```

This is probably because Yahoo! Finance has changed it's behaviour again.  As can be seen below, which is cut&pasted from Yahoo! Finance, the Adj Close is the same as the Close even prior to the 1/4 stock split.

```
Date | Open | High | Low | Close* | Adj Close** | Volume
Aug 09, 2016 | 36.71 | 37.20 | 35.88 | 36.56 | 36.56 | 13,481,100
Aug 09, 2016 | 1/4 Stock Split
Aug 08, 2016 | 37.60 | 37.80 | 37.20 | 37.20 | 37.20 | 46,298,800
```
### Expected behavior

```
> getSymbols("VXX", src = "google")
> head(VXX)
           VXX.Open VXX.High VXX.Low VXX.Close VXX.Volume
2013-11-08   200.60   201.28  194.36    194.48    5567056
2013-11-11   194.76   195.88  193.80    194.08    3263745
2013-11-12   194.28   195.52  192.52    193.36    4523036
2013-11-13   196.16   196.48  192.16    192.60    3806302
2013-11-14   192.36   193.12  190.16    190.56    3798583
2013-11-15   189.32   189.68  188.00    188.12    3643111
```

### Minimal, reproducible example

```r
library(quantmod)

print(getSplits("VXX"))

getSymbols("VXX", src = "yahoo")
head(VXX)

getSymbols("VXX", src = "google")
head(VXX)
```

### Session Info

```r
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] parallel  splines   stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantmod_0.4-9      TTR_0.23-1          xts_0.9-7           zoo_1.8-0           tidyr_0.6.3         caretEnsemble_2.0.0 GenSA_1.1.6        
 [8] optimx_2013.8.7     doParallel_1.0.10   iterators_1.0.8     foreach_1.4.3       dplyr_0.5.0         caret_6.0-76        ggplot2_2.2.1      
[15] lattice_0.20-35     DBI_0.6-1           rsqlserver_1.0      rClr_0.7-4          VGAM_1.0-3          scales_0.4.1        MASS_7.3-47        
[22] plyr_1.8.4          lubridate_1.6.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11       optextras_2016-8.8 class_7.3-14       assertthat_0.2.0   digest_0.6.12      ipred_0.9-6        R6_2.2.1          
 [8] MatrixModels_0.4-1 rlang_0.1.1        curl_2.6           lazyeval_0.2.0     minqa_1.2.4        data.table_1.10.4  SparseM_1.77      
[15] kernlab_0.9-25     car_2.1-4          nloptr_1.0.4       rpart_4.1-11       Matrix_1.2-9       lme4_1.1-13        stringr_1.2.0     
[22] munsell_0.4.3      compiler_3.4.0     numDeriv_2016.8-1  mgcv_1.8-17        nnet_7.3-12        prodlim_1.6.1      tibble_1.3.1      
[29] gridExtra_2.2.1    BB_2014.10-1       quadprog_1.5-5     codetools_0.2-15   ucminf_1.1-4       ModelMetrics_1.1.0 grid_3.4.0        
[36] nlme_3.1-131       gtable_0.2.0       magrittr_1.5       stringi_1.1.5      pbapply_1.3-2      reshape2_1.4.2     setRNG_2013.9-1   
[43] xgboost_0.6-4      lava_1.5           tools_3.4.0        svUnit_0.7-12      Rvmmin_2013-11.12  survival_2.41-3    pbkrtest_0.4-7    
[50] dfoptim_2016.7-1   colorspace_1.3-2   Rcgmin_2013-2.21   quantreg_5.33  
```

**Comment by joshuaulrich** [comment] 2017-07-22 23:10
Thanks for the report.  I'm closing as a duplicate of #174.  This might not be an *exact* duplicate, but it should be fixed as part of the previously-reported issue.

**Closed by joshuaulrich** 2017-07-22 23:10 UTC
