### ISSUE TITLE
Missing Time-Stamp when downloading from Google Finance

### ISSUE THREAD

**Issue by Stefan2015-5** [joshuaulrich/quantmod#150] opened 2017-04-18 13:50 UTC
When downloading from Google Finance, some parts of the time code are NA:

```

> require(quantmod)
> b3<-  getSymbols("GS" ,src="google" , auto.assign=FALSE)   # Goldman
> b3[ 1:44, ]
           GS.Open GS.High GS.Low GS.Close GS.Volume
<NA>        200.60  203.32 197.82   200.72   6515000
<NA>        200.22  200.67 198.07   198.85   6478800
<NA>        198.43  200.00 197.90   199.05   6037100
<NA>        199.05  203.95 198.10   203.73   7851000
<NA>        203.54  204.90 202.00   204.08   7177300
<NA>        203.40  208.44 201.50   208.11   8022400
<NA>        208.34  213.17 207.60   211.88   9044600
<NA>        210.90  214.22 210.40   213.99   6619000
<NA>        200.00  215.13 200.00   213.59   5848800
<NA>        212.20  214.09 210.85   213.23   5360500
<NA>        213.75  214.81 209.10   209.68   6541600
<NA>        209.08  211.44 208.84   210.29   5340300
<NA>        211.09  213.25 209.60   212.97   4980700
<NA>        212.82  213.42 210.65   212.64   6293500
<NA>        213.51  220.17 213.03   220.10   6387500
<NA>        202.00  220.51 212.51   213.07   7855400
<NA>        214.56  214.90 210.60   213.50   7458200
<NA>        213.90  215.08 210.13   211.04   5891100
<NA>        211.08  212.31 208.37   208.78   6002200
<NA>        208.30  212.75 207.29   212.16   7236100
2007-02-01  213.44  213.90 209.73   212.00   5961200
2007-02-02  211.00  213.90 211.00   213.43   3527000
2007-02-05  213.30  213.72 211.50   212.55   3003700
2007-02-06  213.29  215.86 212.70   214.65   3803200
2007-02-07  215.03  215.85 213.10   213.55   3622600
2007-02-08  212.09  215.21 209.81   213.90   5413500
2007-02-09  215.77  219.26 210.58   213.28   9113800
2007-02-12  213.75  214.00 209.87   211.13   5384589
2007-02-13  211.98  213.30 210.47   212.53   4022951
2007-02-14  213.70  219.10 212.79   217.40   7697325
2007-02-15  217.94  218.84 216.41   216.82   3627700
2007-02-16  215.96  217.50 215.02   216.92   3119200
2007-02-20  216.92  221.90 215.97   220.94   6225700
2007-02-21  220.94  221.50 218.16   220.15   5225500
2007-02-22  221.00  222.75 218.00   218.97   4273400
2007-02-23  218.97  219.80 215.55   216.50   5508300
2007-02-26  218.97  218.37 212.66   214.00   5552985
2007-02-27  209.75  210.40 194.65   199.76  18854200
2007-02-28  200.40  203.85 197.79   201.75  15947900
<NA>        197.12  202.70 194.08   199.66  14143801
<NA>        198.20  200.92 195.59   195.67   9843700
<NA>        193.55  197.49 189.85   190.00  13412125
<NA>        190.00  198.20 193.70   197.37  10798973
<NA>        197.37  199.00 195.50   195.59   8459800

```

Always seems to affect january, march, may, october and december irrespective of time series and year.
here is the session info:

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-7 TTR_0.23-1     xts_0.9-7      zoo_1.7-14    

loaded via a namespace (and not attached):
[1] tools_3.3.3     grid_3.3.3      lattice_0.20-34

```

**Comment by joshuaulrich** [comment] 2017-04-18 13:51
Closing as duplicate of #140.

**Closed by joshuaulrich** 2017-04-18 13:51 UTC
