### ISSUE TITLE
Can't download data from Yahoo Finance again.

### ISSUE THREAD

**Issue by Yiming-WANG** [joshuaulrich/quantmod#165] opened 2017-05-28 06:17 UTC
several days ago, it was fixed. (I downloaded the developer version)
It happened again minutes ago. 

d> getSymbols(stockList, src = "yahoo")
Error in curl::curl_download(paste0(yahoo.URL, Symbols.name, "?period1=",  : 
  HTTP error 401.

**Comment by joshuaulrich** [comment] 2017-05-28 12:09
When reporting an issue, please follow the instructions in ["Have a bug report or feature request?" in the contributing guide](https://github.com/joshuaulrich/quantmod/blob/master/CONTRIBUTING.md#have-a-bug-report-or-feature-request).  In this case, you need to:

1. "Ensure your fork and local copy are up-to-date, and verify the bug still exists in the HEAD of the master branch."  (You are not using the latest development version.)
2. "Include ... the output from `sessionInfo()`."

**Comment by hagakure0x** [comment] 2017-05-28 13:04
I have the latest development version installed **quantmod_0.4-9**  and i get the following message after downloading ^GSPC (SPX).

` ^GSPC contains missing values. Some functions will not work if objects contain missing values in the middle of the series. Consider using na.omit(), na.approx(), na.fill(), etc to remove or replace them. `

Earlier today Yahoo returned data as factor, something is being changed as we speak. Probably a good idea just to give it a rest until they have everything in place again.

**Comment by o7g8** [comment] 2017-05-28 15:03
Everything works fine for me. The following code loads YHOO data from Yahoo as expected:

```
library(quantmod)
getSymbols("YHOO")
```

I've installed developer version with:

`devtools::install_github("joshuaulrich/quantmod")`

Here is my `sessionInfo()`:

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-9 TTR_0.23-1     xts_0.9-7      zoo_1.8-0     

loaded via a namespace (and not attached):
[1] compiler_3.4.0  tools_3.4.0     curl_2.6        grid_3.4.0      lattice_0.20-35
```

**Comment by Yiming-WANG** [comment] 2017-05-28 15:44
Sorry, I was using quantmod 0.4-8 last night. 
There is no problem on quantmod 0.4-9.

**Comment by joshuaulrich** [comment] 2017-05-28 15:47
Thanks for confirming!  Closing as a duplicate of #157.

**Closed by joshuaulrich** 2017-05-28 15:47 UTC
Labels: duplicate
