### ISSUE TITLE
getSymbols.MySQL parameter   db.fields , field.names

### ISSUE THREAD

**Issue by howe222** [joshuaulrich/quantmod#125] opened 2016-11-01 12:19 UTC
Hello,

db.fields 	character vector indicating names of fields to retrieve
field.names 	names to assign to returned columns 

giving the following 
 db.fields = c("row_names", "Open", "High", "Low", "Close", "Volume","Adjusted"),
 field.names = c("Date","Open", "High", "Low", "Close", "Volume","Adjusted"),
 
should be excuted but it throwes the exception
               Error in .local(conn, statement, ...) : 
  could not run statement: Unknown column 'date' in 'order clause'

**Comment by joshuaulrich** [comment] 2016-11-01 14:56
Closing as duplicate of #51.

**Closed by joshuaulrich** 2016-11-01 14:56 UTC
